version: "3.7"

services:
  server: 
    build: 
      dockerfile: Dockerfile
      context: .
      target: app
    depends_on: 
      - database
    networks: 
      - postgres
    ports:
      - "8080:8080"
    expose:
      - 8080
    extra_hosts:
      - "host.docker.internal:host-gateway"

  database:
    image: postgres:latest
    restart: always
    environment: 
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres
    expose:
      - 5432
networks:
  postgres:
    driver: bridge